'use client';
import React, {createContext, useState, useEffect } from 'react';
import Head from 'next/head'
import questions from "@/questions.json";
import styles from '@/styles/index.module.css'
import QuestionRow from '@/components/QuestionRow';
import ModuleComponent from '@/components/Module';
import Html5QrcodePlugin from '@/components/Html5QrcodePlugin';
import {QuestionProvider} from '@/components/QuestionProvider'
import Test from '@/components/Test'

export const QuestionContext = createContext();

export default function QrScannerHomePage() {
  const [questionData, setQuestionData] = useState(questions.questions);
  /*const [isModuleVisible, setIsModuleVisible] = useState(false);
  const [isScannerVisible, setIsScannerVisible] = useState(false);
  const [selectedQuestionData, setSelectedQuestionData] = useState(null);

  const [questionBlock, setQuestionBlock] = useState([]);

  useEffect(() => {
    if (questionData.length > 0) {
      let temp = []
      for (let i = 0; i < questionData.length; i++) {
        const question = getQuestionHandler(i);
        const questionComponent = (
          <QuestionRow
            key={question.id} // Don't forget to add a unique key
            onClick={toggleModuleVisibilityText}
            question={question}
          />
        );
        temp.push(questionComponent)
      }
      setQuestionBlock(temp)
    }
  }, [questionData]);

  function getQuestionHandler(questionIndex) {
    return questionData[questionIndex]
  }

  const toggleModuleVisibilityText = (selectedQuestion) => {
    setIsModuleVisible(true);
    setSelectedQuestionData(selectedQuestion); // Store the selected question data
  };*/

  return (
    <>
      <Head>
        <title>Qr Scanner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <QuestionContext.Provider value={questionData} className={styles.main}>
        <Test/>
      </QuestionContext.Provider>
    </>
  )
}
