'use client';
import React, {useState} from 'react';
import Head from 'next/head'
import questions from "@/questions.json";
import styles from '@/styles/index.module.css'
import QuestionRow from '@/components/QuestionRow';
import ModuleComponent from '@/components/Module';
import Html5QrcodePlugin from '@/components/Html5QrcodePlugin';
import { Html5QrcodeScanner } from 'html5-qrcode';

export default function QrScannerHomePage() {
  const [isModuleVisible, setIsModuleVisible] = useState(false);
  const [isScannerVisible, setIsScannerVisible] = useState(false);
  const [selectedQuestion, setSelectedQuestion] = useState(null);

  function getQuestionHandler(questionIndex) { 
    const result = questions.questions[questionIndex];
    return result
  }

  const toggleModuleVisibilityText = (questionData) => {
    setIsModuleVisible(true);
    setSelectedQuestion(questionData); // Store the selected question data
  };

  const getInputFromScan = (scanData) => {
    console.log(scanData)
    setIsScannerVisible(false)
  }

  return (
    <>
      <Head>
        <title>Qr Scanner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        {isScannerVisible? (

          <div className="scanner">
            <Html5QrcodePlugin
                resultFromScan={getInputFromScan}
                />
          </div>

        ) : (

          <div className="questions">

            {isModuleVisible? (<ModuleComponent question={selectedQuestion} onClick={setIsModuleVisible}/>) : ''}
            <h1 className={styles.h1}>QR Scanning Code</h1>
            <QuestionRow onClick={toggleModuleVisibilityText} question={getQuestionHandler(0)} />
            <QuestionRow onClick={toggleModuleVisibilityText} question={getQuestionHandler(1)} />
            <QuestionRow onClick={toggleModuleVisibilityText} question={getQuestionHandler(2)} />

            <div className={styles.nav}>
              <div className={styles.navGroup}>
                <button onClick={setIsScannerVisible} className={styles.scan}>SCAN</button>
                <button className={styles.give_up}>GIVE UP</button>
              </div>
            </div>
          </div>
        )}

        
      </main>
    </>
  )
}
