'use client';
import React, { useEffect, useState } from 'react';
import { Html5QrcodeScanner } from 'html5-qrcode';

import questions from '@/questions.json';
import Head from 'next/head'
import styles from '@/styles/index.module.css'

export default function Home() {
  const [scanResult, setScanResult] = useState(null);
  const [manualSerialNumber, setManualSerialNumber] = useState('');

  useEffect(() => {

    const scanner = new Html5QrcodeScanner('reader', {
      qrbox: {
        width: 250,
        height: 250,
      },

      fps: 6,

    });

    let isScanning = true;

    scanner.render(success, error);

    function success(result) {

      if (isScanning) {

        scanner.clear();
        setScanResult(result);
        isScanning = false; // Set isScanning to false to stop further scanning

      }

    }

    function error(err) {
      console.warn(err);
    }

  }, []);

  function handleManualSerialNumberChange(event) {
    setManualSerialNumber(event.target.value);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div id="reader" className={styles.reader}></div>
        {scanResult ? (
          <div>
            <p>Success: <a href={scanResult}>{scanResult}</a></p>
            <p>Serial Number: {scanResult.slice(-16)}</p>
          </div>
        ) : (
          <div>
            <div id="reader"></div>
            <div className="center-input">
              {manualSerialNumber && (
                <p>Serial Number: {manualSerialNumber.slice(-16)}</p>
              )}
            </div>
          </div>
        )}
      </main>
    </>
  )
}
